const OBFUSCATION_MASK = "Cryptonite submission key mask v1";
const ENCRYPTED_PREFIX = "enc:";

// Restores a key generated by the local encryption helper.
export function decryptApiKey(encryptedValue: string): string {
    if (!encryptedValue.startsWith(ENCRYPTED_PREFIX)) return "";

    try {
        const encodedValue = encryptedValue.slice(ENCRYPTED_PREFIX.length);
        const encryptedBytes = Uint8Array.from(atob(encodedValue), char => char.charCodeAt(0));
        const maskBytes = new TextEncoder().encode(OBFUSCATION_MASK);
        const decryptedBytes = encryptedBytes.map((byte, index) => byte ^ maskBytes[index % maskBytes.length]);

        return new TextDecoder().decode(decryptedBytes);
    }
    catch {
        return "";
    }
}
